[tool.poetry]
name = "VSB"
version = "0.1.0"
description = "A vector search benchmarking suite, built on the Locust framework"
authors = ["Pinecone Systems, Inc. <support@pinecone.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
locust = "^2.29.1"
pandas = "^2.2.1"
google-cloud-storage = "^2.17.0"
grpcio = "^1.64.1"
pyarrow = "^16.1.0"
pinecone-client = {version = "^4.1", extras = ["grpc"]}
tabulate = "^0.9.0"
pydantic = "^2.7.4"
locust-plugins = "^4.4.3"
pgvector = "^0.3.0"
psycopg = "^3.1.19"
hdrhistogram = "^0.10.3"
tenacity = "^8.4.2"
rich = "^13.7.1"

[tool.poetry.scripts]
vsb = "vsb.main:main"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
pytest = "^8.2.2"
flake8 = "^7.1.0"
pre-commit = "^3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
