version: '3.9'

services:
  pgvector:
    image: pgvector/pgvector:0.6.0-pg16
    container_name: vsb_pgvector
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      resources:
        # By default, limit to 8GB RAM & 2 CPU cores - reasonable values which
        # should be sufficient for a range of workloads and typical commodity
        # hardware can support.
        # Adjust as needed for larger workloads.
        limits:
          memory: 8GB
          cpus: '2'
    shm_size: 8GB # Equal to limits.memory.
# To use a persistent volume uncomment this and the 'volumes:' top level
# section below:
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

# volumes:
#   pgdata:
